#!/usr/bin/python
from dogtail.procedural import *

focus.application('firstboot')
focus.frame('')
click('Forward', roleName='push button')
click('Disabled', roleName='menu item')
click('Disabled', roleName='menu item')
click('Disabled', roleName='combo box', raw=True)
click('Enabled', roleName='menu item')
click('Enabled', roleName='combo box', raw=True)
click('Disabled', roleName='menu item')
click('Forward', roleName='push button')
click('Yes', roleName='push button')
click('Permissive', roleName='menu item')
click('Enforcing', roleName='menu item')
click('Enforcing', roleName='combo box', raw=True)
click('Permissive', roleName='menu item')
click('Forward', roleName='push button')
click('Forward', roleName='push button')
click('Network Time Protocol', roleName='page tab', raw=True)
click('Enable Network Time Protocol', roleName='check box')
click('Enable Network Time Protocol', roleName='check box')
activate('clock2.redhat.com', roleName='table cell')
click('Forward', roleName='push button')
click('Forward', roleName='push button')
click('Forward', roleName='push button')
activate('', roleName='text')
click('I have access to a Red Hat Network Satellite or Red Hat Network Proxy. I\'d like to receive software updates from the Satellite or Proxy below:', roleName='radio button')
keyCombo("Tab")
keyCombo("<Control>a")
keyCombo("BackSpace")
type("http://fjs-0-06.rhndev.redhat.com/XMLRPC")
click('Advanced Network Configuration ...', roleName='push button')
focus.dialog('Advanced Network Configuration')
click('I would like to connect to Red Hat Network via an HTTP proxy.', roleName='check box')
click('I would like to connect to Red Hat Network via an HTTP proxy.', roleName='check box')
click('Close', roleName='push button')
click('Forward', roleName='push button')
type("admin")
keyCombo("Tab")
type("dogcode")
click('Forward', roleName='push button')
click('OK', roleName='push button')
keyCombo("BackSpace")
type("dog8code")
click('Forward', roleName='push button')
activate('', roleName='text')
keyCombo("<Control>a")
keyCombo("BackSpace")
type("wesProfile")
click('Forward', roleName='push button')
click('', roleName='text', raw=True)
click('Forward', roleName='push button')
click('Forward', roleName='push button')
click('Continue', roleName='push button')
click('Forward', roleName='push button')
click('Finish', roleName='push button')